### PR TITLE
Restore files permissions on unix like systems (linux, mac os x).

### PR DESCRIPTION
**Pull request by yves-del-medico**
This pull request adresses the issue https://github.com/nearinfinity/node-unzip/issues/6

### CODE REVIEW

**Comment by yves-del-medico** [comment]
Sorry, this is too early to submit this pull request.
I wanted to integrate it first in my forked repo.
So, I close this pull request for the moment.

**Comment by yves-del-medico** [comment]
Hello, I made some modifications to apply permission which apparently were working fine on node-unzip 0.1.2.

I ported my fix on node-unzip 0.1.3, and now I see (not always) an error saying that the file does not exist when
I try to execute the fs.chmod.

It seems that the _readCentralDirectoryFileHeader() is called while the file is still being written to disk and not yet closed.

My feeling is that we should wait until all the files are written to disk before processing the central directory entries.
Any thoughts, ideas ?

**Comment by EvanOxfeld** [comment]
Thanks for the pull request - I'm liking what you have so far. I agree that central directory entry processing should wait until all files have been written to disk or even better just the individual file referenced by the header. Also the fs.chmod calls belong in Extract so not to break the use of Parse for parsing zips without writing files to disk. Probably Extract should inherit from Parse rather than use composition to better support this.

As far as the cause of test failures in 0.1.3, it's probably that the new zip format (introduced in #10) is parsed slower, making the issue with processing central directory entries more apparent.

**Comment by yves-del-medico** [comment]
Thanks for your reply and sorry for my very late answer.

You're right, fs.chmod should not be done in parse.js. I'm not yet familiar enough with the code to say where it should be done.
Maybe we should use the Entry mechanism and some event to post the mode and hope somebody will apply it if he  wants to do so.
Does it make sense ?

Concerning the way to wait for the file(s) being written to disk before processing the central directory entry, I must recognized that I'm still a bit lost to understand which event(s) should be taken into account.

Do you have any hints ?

Thanks

**Comment by EvanOxfeld** [comment]
One thought is that Parse would emit Central Directory File Header events that Extract would listen for. Extract would buffer up all of the update file permissions requests until fstream.Writer emits its 'close' event.

Ideally fstream.Writer would emit some sort of 'close' event when each file finishes getting written to disk, and Extract would update permissions as files are ready, as opposed to all at once after everything's written to disk.

Thoughts?

**Comment by yves-del-medico** [comment]
I think this goes in the right direction. This would be great when we extract all the files as Extract could do the job of synchronizing things and apply permissions if needed.

I'm not sure if this will cover the case when we use only Parse to extract manually a few files.

**Comment by EvanOxfeld** [comment]
For the case when we use Parse to extract a few files, what about something like this?

**edit**: _Updated example to include piping the entry to fs.writeStream_

``` javascript
var readStream  = fs.createReadStream('path/to/archive.zip');
var unzipParser = unzip.Parse();
unzipParser.on('entry', function (entry) {
  var fileName = entry.path;
  if (fileName  === "file_I_want_to_extract") {
    entry.pipe(fs.createWriteStream(fileName)
      .on('close', function() {
        //done writing file to disk
      });
  }
 });
unzipParser.on('centralDirectoryHeader', function (header) {
  if (header.fileName === "file_I_want_to_extract") {
    ...
    //wait until file is written to disk
    ...
    //process header.externalFileAttributes with something like fs.chmod
  }
 });

readStream.pipe(unzipParser);
```

**Comment by yves-del-medico** [comment]
I think this would be good.

**Comment by steffenmllr** [comment]
I'm trying to stream download and unpack a mac.app file which needs the right permissions to be executable and bumped into the same issue. I looked over your code but I couldn't really figure out when to emit a centralDirectoryHeader event.

Any help or progress on this would be appreciated :)

**Comment by viktorku** [comment]
I implemented the approach discussed here in https://github.com/Intermodalics/node-unzip-2/pull/1, which works good for us.

**Pull request closed without merging**
